### ISSUE TITLE
The following error occurred　when run the main.m，I don't know where the variable　’fonk_numara‘ comes from　?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [uguryuzgec/MsRwGWO#1]
'variable or function　'fonk _ Numara '　not recognized，

error occurred　ｍａｉｎ.ｍ(ｌｉｎｅ　５４)

**Comment by uguryuzgec** [comment]
Sorry, we forgot one while translating variable names from Turkish to English.
The variable's name has been changed to func_num. main.m file has been edited.
So, the new version of the code line 54 is given below: 
str = sprintf('Convergence Analysis of FN%d',func_num);
